[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "langchain-openai==0.3.8",
    "langgraph==0.2.73",
    "pydantic==2.10.4",
    "pydantic-settings==2.7.0",
]
